/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package absensi;

/**
 *
 * @author wrahm
 */

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Locale;

import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class Absensi extends javax.swing.JFrame {

/**
 *
 * @author RAHMAT WAHYUDI
 */

    public Absensi() {
        initComponents();
         setLocationRelativeTo(null);

       jLabel6.setText( "<html>Informasi Profil, Email, Nama <br> dan Nomor Induk Mahasiswa (NIM)</html>");
        jLabel6.setMaximumSize(new Dimension(40, Integer.MAX_VALUE));
         Color warna = new Color (244,244,244);
    getContentPane().setBackground(warna);
 
    
    }



public Absensi(String nim, String nama, String username, String jurusan,String telp, String kelamin, String prodi) {
    
        initComponents();
   
        setLocationRelativeTo(null);
             jLabel6.setText( "<html>Informasi Profil, Email, Nama <br> dan Nomor Induk Mahasiswa (NIM)</html>");
               
             jLabel6.setMaximumSize(new Dimension(40, Integer.MAX_VALUE));
            Color warna = new Color (244,244,244);
             getContentPane().setBackground(warna);
          //   jTable1.setBackground(new java.awt.Color(255,255,255));
           
        //     this.jTable1.getTableHeader().setBackground(Color.yellow);
//this.jTable1.getTableHeader().setForeground(Color.yellow);

      lblNama.setText(nama);
      lblNIM.setText(nim);
      lblUsernameprofil.setText(username);
      lblNama2.setText(nama);
      lblJurusan.setText(jurusan);
      lblKelamin.setText(kelamin);
      lblProdi.setText(prodi);
      lblTelp.setText(telp);
                
        //Menampilkan Jam
        try {
                    ActionListener taskPerformer = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                    String Vjam;
                    String noljam = "";
                    String nolmenit = "";
                    String noldetik = "";
                    String nolmilidetik="";
                    Calendar dt = Calendar.getInstance();
                    int jam = dt.get(Calendar.HOUR_OF_DAY);
                    int menit = dt.get(Calendar.MINUTE);
                    int detik = dt.get(Calendar.SECOND);
                    int milidetik = dt.get(Calendar.MILLISECOND);
                    if (jam < 10) {
                        noljam = "0";
                    }
                    if (menit < 10) {
                        nolmenit = "0";
                    }
                    if (detik < 10) {
                        noldetik = "0";
                    }
                      if (milidetik < 10) {
                        nolmilidetik = "0";
                    }
                    String Sjam = noljam + Integer.toString(jam);
                    String Smenit = nolmenit + Integer.toString(menit);
                    String Sdetik = noldetik + Integer.toString(detik);
                    String Smilidetik = nolmilidetik + Integer.toString(milidetik);
                    Vjam = Sjam + ":" + Smenit + ":" + Sdetik;
                    lblJam.setText(Vjam);
                    }};
                    new javax.swing.Timer(100, taskPerformer).start();
                    } catch (Exception e) {
                    System.out.println("Error : " + e);
                    }
        
        //Menampilkan tanggal
 try {
    LocalDate date = LocalDate.now();
   DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", Locale.forLanguageTag("id-ID"));
    DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("yyyy-MM-dd", Locale.forLanguageTag("id-ID"));
      
    String formattedDate = date.format(formatter);
     String formattedDate2 = date.format(formatter2);
    lblTgl.setText(formattedDate);
    lblTgl2.setText(formattedDate);
    lblTgl3.setText(formattedDate2);
} catch (Exception e) {
    System.out.println("Error TGL : " + e.getMessage());
}

 
 
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblJam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnprofil = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnabsen = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnabsensiku = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        lblTgl = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnjadwal = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        pnlProfil = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTelp = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblProdi = new javax.swing.JLabel();
        lblKelamin = new javax.swing.JLabel();
        lblJurusan = new javax.swing.JLabel();
        lblUsernameprofil = new javax.swing.JLabel();
        lblNama2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlAbsen = new javax.swing.JPanel();
        lblTgl3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnPulang = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        lbldiluarjamabsenpulang = new javax.swing.JLabel();
        lbldiluarjamabsenmasuk = new javax.swing.JLabel();
        lblTgl2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlJadwal = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        lblTgl6 = new javax.swing.JLabel();
        lblTgl7 = new javax.swing.JLabel();
        lblTgl9 = new javax.swing.JLabel();
        lblTgl8 = new javax.swing.JLabel();
        lblTgl13 = new javax.swing.JLabel();
        lblTgl10 = new javax.swing.JLabel();
        lblTgl11 = new javax.swing.JLabel();
        lblTgl12 = new javax.swing.JLabel();
        lblTgl14 = new javax.swing.JLabel();
        lblTgl15 = new javax.swing.JLabel();
        lblTgl16 = new javax.swing.JLabel();
        lblTgl17 = new javax.swing.JLabel();
        lblTgl18 = new javax.swing.JLabel();
        lblTgl20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lblTgl21 = new javax.swing.JLabel();
        lblTgl22 = new javax.swing.JLabel();
        lblTgl23 = new javax.swing.JLabel();
        lblTgl24 = new javax.swing.JLabel();
        lblTgl25 = new javax.swing.JLabel();
        lblTgl26 = new javax.swing.JLabel();
        lblTgl27 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pnlAbsensiku = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        lblTgl4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 47, 47));
        jLabel3.setText("Selamat Datang,");

        lblNama.setFont(new java.awt.Font("Montserrat SemiBold", 1, 30)); // NOI18N
        lblNama.setForeground(new java.awt.Color(17, 65, 139));
        lblNama.setText("Rahmat Wahyudi");

        jPanel1.setBackground(new java.awt.Color(17, 65, 139));

        jPanel2.setBackground(new java.awt.Color(17, 65, 139));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ABSENSI MAHASISWA");

        jSeparator1.setBackground(new java.awt.Color(191, 191, 191));

        lblJam.setFont(new java.awt.Font("Montserrat Medium", 0, 24)); // NOI18N
        lblJam.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lblJam, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(17, 65, 139));
        jPanel3.setPreferredSize(new java.awt.Dimension(148, 50));

        btnprofil.setBackground(new java.awt.Color(99, 88, 220));
        btnprofil.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnprofil.setForeground(new java.awt.Color(255, 255, 255));
        btnprofil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profil.png"))); // NOI18N
        btnprofil.setText("PROFIL");
        btnprofil.setBorder(null);
        btnprofil.setContentAreaFilled(false);
        btnprofil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnprofil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprofilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnprofilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnprofilMouseExited(evt);
            }
        });
        btnprofil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnprofil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnprofil, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(17, 65, 139));
        jPanel4.setPreferredSize(new java.awt.Dimension(148, 50));

        btnabsen.setBackground(new java.awt.Color(17, 65, 139));
        btnabsen.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnabsen.setForeground(new java.awt.Color(255, 255, 255));
        btnabsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/absen.png"))); // NOI18N
        btnabsen.setText("ABSEN");
        btnabsen.setBorder(null);
        btnabsen.setContentAreaFilled(false);
        btnabsen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnabsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnabsenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnabsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnabsenMouseExited(evt);
            }
        });
        btnabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabsenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnabsen, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(17, 65, 139));
        jPanel5.setPreferredSize(new java.awt.Dimension(148, 50));

        btnabsensiku.setBackground(new java.awt.Color(17, 65, 139));
        btnabsensiku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnabsensiku.setForeground(new java.awt.Color(255, 255, 255));
        btnabsensiku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/absensi.png"))); // NOI18N
        btnabsensiku.setText("ABSENSIKU");
        btnabsensiku.setBorder(null);
        btnabsensiku.setContentAreaFilled(false);
        btnabsensiku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnabsensiku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnabsensikuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnabsensikuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnabsensikuMouseExited(evt);
            }
        });
        btnabsensiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabsensikuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnabsensiku, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnabsensiku, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(17, 65, 139));
        jPanel6.setPreferredSize(new java.awt.Dimension(148, 50));

        btnlogout.setBackground(new java.awt.Color(17, 65, 139));
        btnlogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.setBorder(null);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        lblTgl.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        lblTgl.setForeground(new java.awt.Color(255, 255, 255));
        lblTgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTgl.setText("Wednesday, 23 May 2023");
        lblTgl.setPreferredSize(new java.awt.Dimension(200, 20));

        jPanel8.setBackground(new java.awt.Color(17, 65, 139));
        jPanel8.setPreferredSize(new java.awt.Dimension(148, 50));

        btnjadwal.setBackground(new java.awt.Color(17, 65, 139));
        btnjadwal.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnjadwal.setForeground(new java.awt.Color(255, 255, 255));
        btnjadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-edit 1.png"))); // NOI18N
        btnjadwal.setText("JADWAL ABSEN");
        btnjadwal.setBorder(null);
        btnjadwal.setContentAreaFilled(false);
        btnjadwal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnjadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjadwalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjadwalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjadwalMouseExited(evt);
            }
        });
        btnjadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjadwalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnjadwal, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel7.setBackground(new java.awt.Color(244, 244, 244));
        jPanel7.setLayout(new java.awt.CardLayout());

        pnlProfil.setBackground(new java.awt.Color(244, 244, 244));
        pnlProfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 106, 106));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Informasi Profil, Email, Nama dan Nomor Induk Mahasiswa(NIM)");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 15));
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlProfil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 56));

        lblNIM.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblNIM.setForeground(new java.awt.Color(17, 65, 139));
        lblNIM.setText("null");
        pnlProfil.add(lblNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        lblTelp.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblTelp.setForeground(new java.awt.Color(17, 65, 139));
        lblTelp.setText("null");
        pnlProfil.add(lblTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabel20.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(17, 65, 139));
        jLabel20.setText("NOMOR TELEPON");
        pnlProfil.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        lblProdi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblProdi.setForeground(new java.awt.Color(17, 65, 139));
        lblProdi.setText("null");
        pnlProfil.add(lblProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        lblKelamin.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblKelamin.setForeground(new java.awt.Color(17, 65, 139));
        lblKelamin.setText("null");
        pnlProfil.add(lblKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 565, -1, -1));

        lblJurusan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblJurusan.setForeground(new java.awt.Color(17, 65, 139));
        lblJurusan.setText("null");
        pnlProfil.add(lblJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 307, -1, -1));

        lblUsernameprofil.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblUsernameprofil.setForeground(new java.awt.Color(17, 65, 139));
        lblUsernameprofil.setText("null");
        pnlProfil.add(lblUsernameprofil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        lblNama2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lblNama2.setForeground(new java.awt.Color(17, 65, 139));
        lblNama2.setText("null");
        pnlProfil.add(lblNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 135, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(17, 65, 139));
        jLabel12.setText("JURUSAN");
        pnlProfil.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(17, 65, 139));
        jLabel13.setText("JENIS KELAMIN");
        pnlProfil.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(17, 65, 139));
        jLabel11.setText("USERNAME");
        pnlProfil.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(17, 65, 139));
        jLabel10.setText("Prodi");
        pnlProfil.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(17, 65, 139));
        jLabel9.setText("NAMA");
        pnlProfil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(17, 65, 139));
        jLabel8.setText("NIM");
        pnlProfil.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 47, 47));
        jLabel4.setText("INFORMASI PROFIL");
        pnlProfil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BoxProfil.png"))); // NOI18N
        pnlProfil.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 625, 630));

        jPanel7.add(pnlProfil, "card3");

        pnlAbsen.setBackground(new java.awt.Color(244, 244, 244));
        pnlAbsen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                pnlAbsenAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pnlAbsen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTgl3.setForeground(new java.awt.Color(255, 255, 255));
        lblTgl3.setText("jLabel19");
        pnlAbsen.add(lblTgl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jSeparator2.setAlignmentX(0.2F);
        jSeparator2.setAlignmentY(0.2F);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        pnlAbsen.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 830, 10));

        btnPulang.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnPulang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnpulang.png"))); // NOI18N
        btnPulang.setBorder(null);
        btnPulang.setBorderPainted(false);
        btnPulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPulangActionPerformed(evt);
            }
        });
        pnlAbsen.add(btnPulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 150, 30));

        btnMasuk.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnabsen.png"))); // NOI18N
        btnMasuk.setBorder(null);
        btnMasuk.setBorderPainted(false);
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        pnlAbsen.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 30));

        lbldiluarjamabsenpulang.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbldiluarjamabsenpulang.setForeground(new java.awt.Color(228, 0, 0));
        lbldiluarjamabsenpulang.setText("DILUAR JAM ABSEN PULANG");
        pnlAbsen.add(lbldiluarjamabsenpulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 135, -1, 20));

        lbldiluarjamabsenmasuk.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        lbldiluarjamabsenmasuk.setForeground(new java.awt.Color(228, 0, 0));
        lbldiluarjamabsenmasuk.setText("DILUAR JAM ABSEN MASUK");
        pnlAbsen.add(lbldiluarjamabsenmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 135, -1, 20));

        lblTgl2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblTgl2.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl2.setText("JUMAT, 30 APRIL 2023");
        pnlAbsen.add(lblTgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, -1, -1));

        jLabel18.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(64, 64, 64));
        jLabel18.setText("ABSEN PULANG");
        pnlAbsen.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(64, 64, 64));
        jLabel17.setText("TANGGAL");
        pnlAbsen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 64, 64));
        jLabel16.setText("ABSEN MASUK");
        pnlAbsen.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 100, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgabsensi.png"))); // NOI18N
        pnlAbsen.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 860, 553));

        jLabel15.setBackground(new java.awt.Color(99, 88, 220));
        jLabel15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(47, 47, 47));
        jLabel15.setText("ABSEN HARIAN");
        pnlAbsen.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel7.add(pnlAbsen, "card2");

        pnlJadwal.setBackground(new java.awt.Color(244, 244, 244));
        pnlJadwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlJadwal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 830, 10));

        jSeparator4.setAlignmentX(0.2F);
        jSeparator4.setAlignmentY(0.2F);
        jSeparator4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        pnlJadwal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 831, 10));

        jSeparator3.setAlignmentX(0.2F);
        jSeparator3.setAlignmentY(0.2F);
        jSeparator3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        pnlJadwal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 831, 10));
        pnlJadwal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 830, 10));
        pnlJadwal.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 830, 10));
        pnlJadwal.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 830, 10));
        pnlJadwal.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 830, 10));
        pnlJadwal.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 830, 10));

        lblTgl6.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl6.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl6.setText("08:00");
        pnlJadwal.add(lblTgl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        lblTgl7.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl7.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl7.setText("KAMIS");
        pnlJadwal.add(lblTgl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblTgl9.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl9.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl9.setText("JUMAT");
        pnlJadwal.add(lblTgl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        lblTgl8.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl8.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl8.setText("SELASA");
        pnlJadwal.add(lblTgl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblTgl13.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl13.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl13.setText("SENIN");
        pnlJadwal.add(lblTgl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblTgl10.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl10.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl10.setText("RABU");
        pnlJadwal.add(lblTgl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, -1, 20));

        lblTgl11.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl11.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl11.setText("MINGGU");
        pnlJadwal.add(lblTgl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 305, -1, 40));

        lblTgl12.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl12.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl12.setText("SABTU");
        pnlJadwal.add(lblTgl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        lblTgl14.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl14.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl14.setText("08:00");
        pnlJadwal.add(lblTgl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 198, -1, -1));

        lblTgl15.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl15.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl15.setText("08:00");
        pnlJadwal.add(lblTgl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        lblTgl16.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl16.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl16.setText("08:00");
        pnlJadwal.add(lblTgl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        lblTgl17.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl17.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl17.setText("LIBUR");
        pnlJadwal.add(lblTgl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        lblTgl18.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl18.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl18.setText("LIBUR");
        pnlJadwal.add(lblTgl18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        lblTgl20.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl20.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl20.setText("08:00");
        pnlJadwal.add(lblTgl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(64, 64, 64));
        jLabel19.setText("JAM PULANG");
        pnlJadwal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(64, 64, 64));
        jLabel21.setText("HARI");
        pnlJadwal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(64, 64, 64));
        jLabel22.setText("JAM MASUK");
        pnlJadwal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel25.setBackground(new java.awt.Color(99, 88, 220));
        jLabel25.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(47, 47, 47));
        jLabel25.setText("JADWAL ABSEN");
        pnlJadwal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        pnlJadwal.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 830, 10));

        lblTgl21.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl21.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl21.setText("16:00");
        pnlJadwal.add(lblTgl21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        lblTgl22.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl22.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl22.setText("16:00");
        pnlJadwal.add(lblTgl22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        lblTgl23.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl23.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl23.setText("16:00");
        pnlJadwal.add(lblTgl23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        lblTgl24.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl24.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl24.setText("16:00");
        pnlJadwal.add(lblTgl24, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        lblTgl25.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl25.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl25.setText("16:00");
        pnlJadwal.add(lblTgl25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, -1, -1));

        lblTgl26.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl26.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl26.setText("LIBUR");
        pnlJadwal.add(lblTgl26, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 290, 40, -1));

        lblTgl27.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTgl27.setForeground(new java.awt.Color(47, 47, 47));
        lblTgl27.setText("LIBUR");
        pnlJadwal.add(lblTgl27, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 320, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgabsensi.png"))); // NOI18N
        pnlJadwal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 860, 553));

        jPanel7.add(pnlJadwal, "card2");

        pnlAbsensiku.setBackground(new java.awt.Color(244, 244, 244));
        pnlAbsensiku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "HARI", "TANGGAL", "JAM MASUK", "JAM PULANG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        pnlAbsensiku.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 845, 520));

        lblTgl4.setForeground(new java.awt.Color(255, 255, 255));
        lblTgl4.setText("jLabel19");
        pnlAbsensiku.add(lblTgl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel24.setBackground(new java.awt.Color(99, 88, 220));
        jLabel24.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(47, 47, 47));
        jLabel24.setText("ABSENSIKU");
        pnlAbsensiku.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        jPanel7.add(pnlAbsensiku, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void getData() {
try {
     
   String nim = lblNIM.getText();
   java.sql.Connection conn = (java.sql.Connection) Koneksi.getKoneksi();
   java.sql.Statement stm = conn.createStatement();
  String query = "SELECT CAST(@no:=@no+1 AS UNSIGNED) AS NO, " 
             + "DATE_FORMAT(tanggal, '%W, %d %M %Y') AS 'TANGGAL', " 
             + "MIN(CASE WHEN keterangan = 'Absen Masuk' AND TIME(waktu) BETWEEN '07:00' AND '09:00' THEN waktu END) AS 'JAM MASUK', "
             + "MAX(CASE WHEN keterangan = 'Absen Pulang' AND TIME(waktu) BETWEEN '16:00' AND '18:00' THEN waktu END) AS 'JAM PULANG' "
             + "FROM absensi, (SELECT @no:=0) r WHERE nim ='" + nim + "' "
             + "GROUP BY tanggal";

   java.sql.ResultSet sql = stm.executeQuery(query);
   jTable1.setModel(DbUtils.resultSetToTableModel(sql)); 
 } catch (SQLException e) {
    System.out.println(e.getMessage());
 }

}




    private void btnprofilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprofilMouseEntered
        setColorLeft(jPanel3);

        
    }//GEN-LAST:event_btnprofilMouseEntered

    private void btnprofilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprofilMouseExited
        resetColorLeft(jPanel3);
        
    }//GEN-LAST:event_btnprofilMouseExited

    private void btnprofilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofilActionPerformed
      //  cardLayout.show(jPanel7, "pnlProfil");
      pnlProfil.setVisible(true);
      pnlAbsen.setVisible(false);
       pnlAbsensiku.setVisible(false);
           pnlJadwal.setVisible(false);
        
    }//GEN-LAST:event_btnprofilActionPerformed

    private void btnprofilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprofilMouseClicked
        // TODO add your handling code here:
    

    }//GEN-LAST:event_btnprofilMouseClicked

    private void btnabsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabsenMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnabsenMouseClicked

    private void btnabsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabsenMouseEntered
        // TODO add your handling code here:
          setColorLeft(jPanel4);
    }//GEN-LAST:event_btnabsenMouseEntered

    private void btnabsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabsenMouseExited
        // TODO add your handling code here:
        resetColorLeft(jPanel4);
    }//GEN-LAST:event_btnabsenMouseExited

    private void btnabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabsenActionPerformed
        // TODO add your handling code here:
         //cardLayout.show(jPanel7, "pnlAbsen");
        LocalDate hari = LocalDate.now();
    System.out.println(hari.getDayOfWeek().name());
    if (hari.getDayOfWeek() == DayOfWeek.SATURDAY || hari.getDayOfWeek() == DayOfWeek.SUNDAY ) {
    
            JOptionPane.showMessageDialog(null, "Tidak Ada Absen Hari Ini karena Libur", "Tidak Ada Absen", JOptionPane.ERROR_MESSAGE);
  
    } else {
        pnlAbsen.setVisible(true);
        pnlProfil.setVisible(false);
          pnlAbsensiku.setVisible(false);
    }
    try {
// jam absen masuk
String sqlMasuk = "SELECT start, finish FROM jam WHERE id_jam = 0";
java.sql.Connection conMasuk = (java.sql.Connection) Koneksi.getKoneksi();
java.sql.PreparedStatement stmntMasuk = conMasuk.prepareStatement(sqlMasuk);

ResultSet rsMasuk = stmntMasuk.executeQuery();

LocalTime startMasuk = null;
LocalTime finishMasuk = null;

while (rsMasuk.next()) {
    startMasuk = rsMasuk.getTime("start").toLocalTime();
    finishMasuk = rsMasuk.getTime("finish").toLocalTime();
}

// Query untuk jam absen pulang
String sqlPulang = "SELECT start, finish FROM jam WHERE id_jam = 1";
java.sql.Connection conPulang = (java.sql.Connection) Koneksi.getKoneksi();
java.sql.PreparedStatement stmntPulang = conPulang.prepareStatement(sqlPulang);

ResultSet rsPulang = stmntPulang.executeQuery();

LocalTime startPulang = null;
LocalTime finishPulang = null;

while (rsPulang.next()) {
    startPulang = rsPulang.getTime("start").toLocalTime();
    finishPulang = rsPulang.getTime("finish").toLocalTime();
}

// Cek waktu lokal saat ini
LocalTime localTime = LocalTime.now();

// hide/munculkan tombol absen masuk jika jam sesuai dengan db
if (localTime.isAfter(startMasuk) && localTime.isBefore(finishMasuk)) {
    btnMasuk.setVisible(true);
       lbldiluarjamabsenmasuk.setVisible(false);
    System.out.println("Jam Absen Masuk");
} else {
    btnMasuk.setVisible(false);
     lbldiluarjamabsenmasuk.setVisible(true);
    System.out.println("Diluar Jam Absen Masuk");
}

// hide/munculkan tombol absen plg jika jam sesuai dengan db
if (localTime.isAfter(startPulang) && localTime.isBefore(finishPulang)) {
    btnPulang.setVisible(true);
      lbldiluarjamabsenpulang.setVisible(false);
    System.out.println("Jam Absen Pulang");
   
} else {
    btnPulang.setVisible(false);
        lbldiluarjamabsenpulang.setVisible(true);
    System.out.println("Diluar Jam Absen Pulang");
}

// Tampilkan waktu start dan finish untuk debug
System.out.println("Jam Absen Masuk: start = " + startMasuk + ", finish = " + finishMasuk);
System.out.println("Jam Absen Pulang: start = " + startPulang + ", finish = " + finishPulang);
} catch (SQLException ex) {
System.out.println("Gagal");
}
         
     
    }//GEN-LAST:event_btnabsenActionPerformed

    private void btnabsensikuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabsensikuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnabsensikuMouseClicked

    private void btnabsensikuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabsensikuMouseEntered
        // TODO add your handling code here:
         setColorLeft(jPanel5);
    }//GEN-LAST:event_btnabsensikuMouseEntered

    private void btnabsensikuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnabsensikuMouseExited
        // TODO add your handling code here:
         resetColorLeft(jPanel5);
    }//GEN-LAST:event_btnabsensikuMouseExited

    private void btnabsensikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabsensikuActionPerformed
        // TODO add your handling code here:
           getData();
        
       pnlAbsensiku.setVisible(true);
          pnlAbsen.setVisible(false);
        pnlProfil.setVisible(false);
         pnlJadwal.setVisible(false);
    }//GEN-LAST:event_btnabsensikuActionPerformed

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
        // TODO add your handling code here:
     
     try {
    int keluar = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (keluar == JOptionPane.YES_OPTION) {
        this.dispose();
        Login a = new Login();
        a.setVisible(true);
    }
} catch (Exception e) {
    System.out.println("Error: " + e.getMessage());
}

    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        // TODO add your handling code here:
         setColorLeft(jPanel6);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        // TODO add your handling code here:
        resetColorLeft(jPanel6);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        //  TODO add your handling code here:
       
    try {
        String sql = "SELECT COUNT(*) FROM absensi INNER JOIN jam ON TIME(waktu) BETWEEN jam.start AND jam.finish WHERE nim = ? AND tanggal = ? AND jam.id_jam = 0";
        java.sql.Connection con = (java.sql.Connection) Koneksi.getKoneksi();
        java.sql.PreparedStatement stmnt = con.prepareStatement(sql);
        stmnt.setString(1, lblNIM.getText());
        LocalDate localDate = LocalDate.now();
        java.sql.Date date = java.sql.Date.valueOf(localDate);
        stmnt.setDate(2, date);
        java.sql.ResultSet rs = stmnt.executeQuery();
        if (rs.next() && rs.getInt(1) > 0) {
          
            JOptionPane.showMessageDialog(null, "Anda sudah melakukan absen masuk sebelumnya atau dilakukan di luar jam absen", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            sql = "INSERT INTO absensi (nim, nama, tanggal, waktu, keterangan) " +
                  "VALUES (?, ?, ?, ?, ?)";
            stmnt = con.prepareStatement(sql);
            stmnt.setString(1, lblNIM.getText());
            stmnt.setString(2, lblNama2.getText());
            localDate = LocalDate.now();
            date = java.sql.Date.valueOf(localDate);
            stmnt.setDate(3, date);
            LocalTime localTime = LocalTime.now();
            java.sql.Time sqlTime = java.sql.Time.valueOf(localTime);
            stmnt.setTime(4, sqlTime);
            stmnt.setString(5, "Absen Masuk");
            stmnt.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Absen Masuk");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Absen Masuk");
        System.out.println(e.getMessage());
    }
    
    
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnPulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPulangActionPerformed
        // TODO add your handling code here:
       try {
        String sql = "SELECT COUNT(*) FROM absensi INNER JOIN jam ON TIME(waktu) BETWEEN jam.start AND jam.finish WHERE nim = ? AND tanggal = ? AND jam.id_jam = 1";
        java.sql.Connection con = (java.sql.Connection) Koneksi.getKoneksi();
        java.sql.PreparedStatement stmnt = con.prepareStatement(sql);
        stmnt.setString(1, lblNIM.getText());
        LocalDate localDate = LocalDate.now();
        java.sql.Date date = java.sql.Date.valueOf(localDate);
        stmnt.setDate(2, date);
        java.sql.ResultSet rs = stmnt.executeQuery();
        if (rs.next() && rs.getInt(1) > 0) {
          
            JOptionPane.showMessageDialog(null, "Anda sudah melakukan absen Pulang sebelumnya atau dilakukan di luar jam absen", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            sql = "INSERT INTO absensi (nim, nama, tanggal, waktu, keterangan) " +
                  "VALUES (?, ?, ?, ?, ?)";
            stmnt = con.prepareStatement(sql);
            stmnt.setString(1, lblNIM.getText());
            stmnt.setString(2, lblNama2.getText());
            localDate = LocalDate.now();
            date = java.sql.Date.valueOf(localDate);
            stmnt.setDate(3, date);
            LocalTime localTime = LocalTime.now();
            java.sql.Time sqlTime = java.sql.Time.valueOf(localTime);
            stmnt.setTime(4, sqlTime);
            stmnt.setString(5, "Absen Pulang");
            stmnt.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Absen Pulang");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Absen Pulang");
        System.out.println(e.getMessage());
    }
    

    }//GEN-LAST:event_btnPulangActionPerformed

    private void btnjadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjadwalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnjadwalMouseClicked

    private void btnjadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjadwalMouseEntered
        // TODO add your handling code here:
         setColorLeft(jPanel8);
    }//GEN-LAST:event_btnjadwalMouseEntered

    private void btnjadwalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjadwalMouseExited
        // TODO add your handling code here:
           resetColorLeft(jPanel8);
    }//GEN-LAST:event_btnjadwalMouseExited

    private void btnjadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjadwalActionPerformed
        // TODO add your handling code here:
        
          pnlAbsen.setVisible(false);
        pnlProfil.setVisible(false);
          pnlAbsensiku.setVisible(false);
          pnlJadwal.setVisible(true);
    }//GEN-LAST:event_btnjadwalActionPerformed

    private void pnlAbsenAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlAbsenAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAbsenAncestorMoved

    public void setColor(JPanel p) {
        p.setBackground(new Color(124,146,160));
    
    }
    public void setColorLeft(JPanel p) {
        p.setBackground(new Color(38, 82, 148));
    }
    public void setColorRed(JPanel p) {
        p.setBackground(new Color(255,0,0));
    }
    public void resetColor(JPanel p1) {
        p1.setBackground(new Color(58,71,80));
    }
    public void resetColorLeft(JPanel p1) {
        p1.setBackground(new Color(17, 65, 139));
    }


/**
 *
 * @author RAHMAT WAHYUDI
 */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnPulang;
    private javax.swing.JButton btnabsen;
    private javax.swing.JButton btnabsensiku;
    private javax.swing.JButton btnjadwal;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnprofil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    public boolean isCellEditable(int row, int column) {
        return false;
    }
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblKelamin;
    public final javax.swing.JLabel lblNIM = new javax.swing.JLabel();
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNama2;
    private javax.swing.JLabel lblProdi;
    private javax.swing.JLabel lblTelp;
    private javax.swing.JLabel lblTgl;
    private javax.swing.JLabel lblTgl10;
    private javax.swing.JLabel lblTgl11;
    private javax.swing.JLabel lblTgl12;
    private javax.swing.JLabel lblTgl13;
    private javax.swing.JLabel lblTgl14;
    private javax.swing.JLabel lblTgl15;
    private javax.swing.JLabel lblTgl16;
    private javax.swing.JLabel lblTgl17;
    private javax.swing.JLabel lblTgl18;
    private javax.swing.JLabel lblTgl2;
    private javax.swing.JLabel lblTgl20;
    private javax.swing.JLabel lblTgl21;
    private javax.swing.JLabel lblTgl22;
    private javax.swing.JLabel lblTgl23;
    private javax.swing.JLabel lblTgl24;
    private javax.swing.JLabel lblTgl25;
    private javax.swing.JLabel lblTgl26;
    private javax.swing.JLabel lblTgl27;
    private javax.swing.JLabel lblTgl3;
    private javax.swing.JLabel lblTgl4;
    private javax.swing.JLabel lblTgl6;
    private javax.swing.JLabel lblTgl7;
    private javax.swing.JLabel lblTgl8;
    private javax.swing.JLabel lblTgl9;
    private javax.swing.JLabel lblUsernameprofil;
    private javax.swing.JLabel lbldiluarjamabsenmasuk;
    private javax.swing.JLabel lbldiluarjamabsenpulang;
    private javax.swing.JPanel pnlAbsen;
    private javax.swing.JPanel pnlAbsensiku;
    private javax.swing.JPanel pnlJadwal;
    private javax.swing.JPanel pnlProfil;
    // End of variables declaration//GEN-END:variables
}
